version: '3.5'

services:
  app:
    image: app
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/usr/src/app/
    environment:
      - dsn=postgres://postgres:postgres@db:5432/praktikum?sslmode=disable
    ports:
      - "9000:9000"
    depends_on:
      - db
    command: sh -c '/usr/src/app/docker/wait-for-it.sh -t 5 db:5432 -- app'
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=praktikum
    ports:
      - '5432:5432'